#!/usr/bin/env perl

Import qw ( env INCLUDE LIB BIN BUILD OBJ);

my $STAR = $ENV{'STAR'};
my $ROOTSYS = $ENV{'ROOTSYS'};
my $STAR_LIB = $ENV{'STAR_LIB'};

$INCLUDE =~ s/#//;

my $CXXFLAGS = $env->{CXXFLAGS};
my $CPPFLAGS = $env->{CPPFLAGS}. " -IStRoot" . " -IStRoot/RTS/src" . " -I/usr/include/libxml2 -IQtRoot/qtgui/inc";
my $CPPPATH = $env->{CPPPATH} . $main::PATH_SEPARATOR . $env->{Packages}->{QT}->{INCDIR};
my $LIBPATH  = $env->{LIBPATH} . $main::PATH_SEPARATOR . $env->{Packages}->{QT}->{LIBDIR};
my $SOFLAGS  = $env->{SOFLAGS};
my $Libraries = $env->{ROOTLIBS}. " -L$STAR_LIB -lxml2 -ldl -lRTS -lStJevpServer -lStJevpPlot -lStPDFUtilities";
my $LIBS = $env->{LIBS}." ".$env->{Packages}->{QT}->{LIBS};


print "include -> $INCLUDE\n";

print "qt dirs::\n:   $env->{Packages}->{QT}->{INCDIR}\n------------------\n";


$env1 = $env->clone('Libraries' => $Libraries,
		    'LIBPATH'   => $LIBPATH,
		    'CXXFLAGS'  => $CXXFLAGS,
		    'CPPFLAGS'  => $CPPFLAGS,
		    'EXTRA_SOFLAGS' => undef,
		    'CPPPATH'   => $CPPPATH,
		    'LIBS'      => $LIBS );

print "JML Conscript\n";
print "\tLibraries = $Libraries\n";
print "\tCPPPATH   = $CPPPATH\n";
print "\tLIBPATH   = $LIBPATH\n";
print "\tSOFLAGS   = $SOFLAGS\n";
print "\tCXXFLAGS  = $CXXFLAGS\n";
print "\tCPPFLAGS  = $CPPFLAGS\n";

#Program $env1 'hello', 'StJevpServer/hello.C'; 
#Program $env1 'server', 'StJevpServer/server.C';
#Program $env1 'build', 'StJevpPlot/build.C';
#Program $env1 'basePlotBuilder', 'StJevpBuilders/basePlotBuilder.C';
Program $env1 'hltDisplay', qw(hltDisplay.C);
#Install $envRTS $BIN, $prog;
#Program $env1 'newproject', 'StJevpBuilders/newproject.C';
#Program $env1 'hltphi', 'StJevpBuilders/hltphi.C';
#Program $env1 'presenter', 'StJevpPresenter/presenter.C';
#Program $env1 'example', 'StJevpPresenter/example.C';
